mode: "deployment"
config:
  exporters:
    prometheus:
      endpoint: "${MY_POD_IP}:8888"
      resource_to_telemetry_conversion:
        enabled: true
  processors:
    batch: {}
  extensions:
    health_check: {}
    pprof: {}
    zpages: {}
  service:
    telemetry:
      metrics:
        address: ""
    extensions: [health_check, pprof, zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]
ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics
