{
 "title": "Flow Monitor 2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jina_receiving_request_seconds_count, jina_namespace)"
    }
   },
   {
    "name": "executor",
    "query": {
     "query": "label_values(jina_document_processed_created{jina_namespace=\"$namespace\"}, runtime_name)"
    }
   },
   {
    "name": "executor_k8s",
    "query": {
     "query": "label_values(jina_document_processed_created{jina_namespace=\"$namespace\"}, jina_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " Metrics and Logs Dashboard for Namespace ${namespace}"
   }
  },
  {
   "title": "Flow Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Traces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "limit": 20,
       "query": "{ .k8s.namespace.name = \"$namespace\" }"
      }
     ]
    }
   ]
  },
  {
   "title": "Flow Deployment Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Deployment Logs",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "{namespace=\"jcloud\", pod!~\".*api-manager.*\", pod=~\"jcloud-operator.*\", container=\"jcloud-operator\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway Logs",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=\"gateway\", container=\"gateway\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor  Logs: [$executor_k8s]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "executor_k8s",
   "collapsed": true,
   "panels": [
    {
     "title": "[$executor_k8s]",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", pod=~\"^$executor_k8s.*\", container=\"executor\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\", image!=\"\", service=\"kube-prometheus-stack-kubelet\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", service=\"kube-prometheus-stack-kubelet\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", service=\"kubecost-prom-kube-prometh-kubelet\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volume Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}  / 1000000) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IOPS(Reads+Writes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ThroughPut(Read+Write)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current Storage IO",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]))"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", namespace=\"$namespace\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Request Gateway received",
     "type": "stat",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (runtime_name) (jina_receiving_request_seconds_count{runtime_name=~\"gateway.*\", jina_namespace=\"$namespace\"})",
       "legendFormat": "{{jina_instance_name}}"
      }
     ]
    },
    {
     "title": "Time elapsed between receiving and responding in the Gateway",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jina_receiving_request_seconds_sum{jina_namespace=\"$namespace\", runtime_name=~\"gateway.*\"}[30m]) / rate(jina_receiving_request_seconds_count{jina_namespace=\"$namespace\", runtime_name=~\"gateway.*\"}[30m])",
       "legendFormat": "{{jina_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of Request processed by the Gateway per minute",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by (jina_pod_name) (increase(jina_receiving_request_seconds_count{jina_namespace=\"$namespace\", runtime_name=~\"gateway.*\"}[1m]))",
       "legendFormat": "{{runtime_name}}"
      }
     ]
    },
    {
     "title": "Failed requests returned by the Gateway per minute",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "expr": "sum by (jina_pod_name) (sum_over_time(jina_failed_requests_total{jina_namespace=\"$namespace\", runtime_name=~\"gateway.*\"}[1m]))",
       "legendFormat": "{{runtime_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executors Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "Namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Documents processed",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (runtime_name) (jina_document_processed_total{jina_namespace=\"$namespace\"})",
       "legendFormat": "{{runtime_name}}"
      }
     ]
    },
    {
     "title": "Total Number of Request processed over time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum by (jina_pod_name) (jina_receiving_request_seconds_count{jina_namespace=\"$namespace\", runtime_name!~\"gateway.*\"})",
       "legendFormat": "{{runtime_name}}"
      }
     ]
    },
    {
     "title": "Failed requests returned by the Executor per minute",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "sum by (jina_pod_name) (sum_over_time(jina_failed_requests_total{jina_namespace=\"$namespace\", runtime_name!~\"gateway.*\"}[1m]))",
       "legendFormat": "{{runtime_name}}"
      }
     ]
    },
    {
     "title": "Time elapsed between receiving and responding in the Executor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jina_receiving_request_seconds_sum{jina_namespace=\"$namespace\", runtime_name!~\"gateway.*\"}[1m]) / (rate(jina_receiving_request_seconds_count{jina_namespace=\"$namespace\", runtime_name!~\"gateway.*\"}[1m]) > 0 ) or rate(jina_receiving_request_seconds_count{jina_namespace=\"$namespace\", runtime_name!~\"gateway.*\"}[1m])  > bool 0",
       "legendFormat": "{{jina_pod_name}}"
      }
     ]
    },
    {
     "title": "Time spend calling the Executor method link to the endpoint",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jina_process_request_seconds_sum{jina_namespace=\"$namespace\", runtime_name!~\"gateway.*\", executor_endpoint!=\"_jina_dry_run_\"}[5m]) / rate(jina_process_request_seconds_count{jina_namespace=\"$namespace\", runtime_name!~\"gateway.*\", executor_endpoint!=\"_jina_dry_run_\"}[5m])",
       "legendFormat": "executor: {{jina_pod_name}},  endpoint: {{executor_endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}